spring:
  profiles:
    active: default, db-maria, os-window, bot-dev, scheduler
  datasource:
    driver-class-name: # 입력해야 합니다.
    username: # 입력해야 합니다.
    password: # 입력해야 합니다.
    url: # 입력해야 합니다.
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: # 입력해야 합니다.
    properties:
      hibernate:
        format_sql: true # log
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
        default_batch_fetch_size: 100

logging:
  level:
    root: INFO
    infoqoch:
      dictionarybot: DEBUG
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    path: # 입력해야 합니다.
    max-size: 10MB

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

telegram:
  token: # 입력해야 합니다.
  user:
    promotion-to-admin: # 입력해야 합니다.

---

spring:
  config:
    activate:
      on-profile: db-mem
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        jdbc:
          batch_size: 500
