spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    url: jdbc:h2:mem:test
    url: jdbc:h2:tcp://localhost/~/dic
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
#        jdbc:
#          batch_size: 500

logging:
  level:
    root: info
    infoqoch: debug

logging.level:
  org.hibernate.SQL: debug

telegram:
  token: "1959903402:AAFfvMCssvDcESLewCDvj5WZk83cbnIZ08o"