spring:
  profiles:
    active: default, window, dev
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        jdbc:
          batch_size: 500

logging:
  level:
    root: info
    infoqoch: debug
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
  file:
    path: # 입력해야 합니다.
    max-size: 10MB

logging.level:
  org.hibernate.SQL: debug

telegram:
  token: # 입력해야 합니다.